[package]
name = "multithread_server"
version = "0.1.0"
authors = ["treug0lnik041 <mark.jedi@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
